# Generated by Django 5.1.6 on 2025-03-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='hAxqZsaa3E', max_length=255),
        ),
    ]
