# Generated by Django 5.1.6 on 2025-04-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistapplication',
            name='submitDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
