# Generated by Django 5.1.6 on 2025-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_releasedate'),
        ('users', '0002_alter_artistapplication_submitdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedAlbums',
            field=models.ManyToManyField(related_name='likedAlbums_users', to='albums.album'),
        ),
    ]
