# Generated by Django 5.1.6 on 2025-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='yihBqViHFW', max_length=255),
        ),
    ]
