# Generated by Django 5.1.6 on 2025-03-11 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_userid_album_user_remove_album_songs_and_more'),
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(default=uuid.uuid4, related_name='users', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(default=models.CharField(max_length=10, unique=True), max_length=255),
        ),
    ]
