# Generated by Django 5.1.6 on 2025-03-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='zigNqdq08w', max_length=255),
        ),
    ]
