# Generated by Django 5.1.6 on 2025-03-11 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_songs'),
        ('users', '0003_user_albums_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(default=uuid.uuid4, related_name='albums_users', to='albums.album'),
        ),
    ]
