# Generated by Django 5.1.6 on 2025-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_likedalbums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistapplication',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='rejectionReason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20),
        ),
    ]
