# Generated by Django 5.1.6 on 2025-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='oR2NJAjV36', max_length=255),
        ),
    ]
