# Generated by Django 5.1.6 on 2025-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='albums',
        ),
    ]
