# Generated by Django 5.1.6 on 2025-03-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistapplication',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='website',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='youtube',
        ),
    ]
