# Generated by Django 5.1.6 on 2025-03-12 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_remove_album_songs'),
        ('users', '0005_remove_user_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(default=uuid.uuid4, related_name='albums_users', to='albums.album'),
        ),
    ]
