# Generated by Django 5.1.6 on 2025-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_album_primarygenre_alter_album_user'),
        ('songs', '0009_song_lyric_song_views_alter_song_album_and_more'),
        ('users', '0008_user_biography_user_facebook_user_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='albums',
            field=models.ManyToManyField(default=list, related_name='albums_users', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='songs',
            field=models.ManyToManyField(default=list, related_name='songs_users', to='songs.song'),
        ),
    ]
