# Generated by Django 5.1.6 on 2025-03-17 10:08

import Sportify_Server.mixin
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_song_lyric_song_views_alter_song_album_and_more'),
        ('users', '0010_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primaryGenre', models.CharField(default=None, max_length=255, validators=[Sportify_Server.mixin.GenreMixin.validate_genres])),
                ('secondaryGenre', models.CharField(default=None, max_length=255, validators=[Sportify_Server.mixin.GenreMixin.validate_genres])),
                ('biography', models.CharField(max_length=1000)),
                ('achievements', models.CharField(max_length=1000)),
                ('website', models.URLField(blank=True, default=None, max_length=255)),
                ('instagram', models.URLField(blank=True, default=None, max_length=255)),
                ('twitter', models.URLField(blank=True, default=None, max_length=255)),
                ('facebook', models.URLField(blank=True, default=None, max_length=255)),
                ('youtube', models.URLField(blank=True, default=None, max_length=255)),
                ('reason', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(default=list, related_name='songs_applications', to='songs.song')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_artist_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artist_applications',
            },
        ),
    ]
