# Generated by Django 5.1.6 on 2025-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_artistapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('vietnam', 'Vietnam'), ('usa', 'United States'), ('uk', 'United Kingdom'), ('france', 'France'), ('germany', 'Germany'), ('japan', 'Japan'), ('china', 'China'), ('south_korea', 'South Korea'), ('canada', 'Canada'), ('australia', 'Australia'), ('italy', 'Italy'), ('spain', 'Spain'), ('russia', 'Russia'), ('brazil', 'Brazil'), ('india', 'India'), ('mexico', 'Mexico'), ('netherlands', 'Netherlands'), ('switzerland', 'Switzerland'), ('sweden', 'Sweden'), ('singapore', 'Singapore'), ('uae', 'United Arab Emirates'), ('saudi_arabia', 'Saudi Arabia'), ('south_africa', 'South Africa')], default='vietnam', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('artist', 'Artist'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('active', 'Active')], default='pending', max_length=10),
        ),
    ]
