# Generated by Django 5.1.6 on 2025-03-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
    ]
