# Generated by Django 5.1.6 on 2025-03-08 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='thumbnail_id',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='userId',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
