# Generated by Django 5.1.6 on 2025-03-26 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20250325_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='releaseDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
