# Generated by Django 5.1.6 on 2025-03-08 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
