# Generated by Django 5.1.6 on 2025-03-11 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_releasedate'),
        ('songs', '0004_alter_song_albumid_alter_song_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='userId',
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='user_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='albums', to='songs.song'),
        ),
    ]
