# Generated by Django 5.1.6 on 2025-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_userid_album_user_remove_album_songs_and_more'),
        ('songs', '0005_remove_song_albumid_remove_song_userid_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='songs_albums', to='songs.song'),
        ),
    ]
