# Generated by Django 5.1.6 on 2025-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
    ]
