# Generated by Django 5.1.6 on 2025-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_remove_album_songs'),
        ('songs', '0006_alter_song_album_alter_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='songs_albums', to='songs.song'),
        ),
    ]
