# Generated by Django 5.1.6 on 2025-03-15 09:23

import Sportify_Server.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='primaryGenre',
            field=models.JSONField(default=list, validators=[Sportify_Server.mixin.GenreMixin.validate_genres]),
        ),
    ]
