# Generated by Django 5.1.6 on 2025-03-17 09:18

import Sportify_Server.mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_album_primarygenre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='primaryGenre',
            field=models.CharField(max_length=255, validators=[Sportify_Server.mixin.GenreMixin.validate_genres]),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
