# Generated by Django 5.1.6 on 2025-03-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_album_primarygenre_alter_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='primaryGenre',
            new_name='genre',
        ),
    ]
