# Generated by Django 5.1.6 on 2025-03-27 16:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('releaseDate', models.DateField(default=django.utils.timezone.now)),
                ('thumbnailUrl', models.URLField()),
                ('audioUrl', models.URLField()),
                ('videoUrl', models.URLField()),
                ('lyrics', models.CharField(default='', max_length=8000)),
                ('duration', models.IntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
