# Generated by Django 5.1.6 on 2025-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='releaseDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
