# Generated by Django 5.1.6 on 2025-03-26 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='releaseDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
