# Generated by Django 5.1.6 on 2025-03-08 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_userid'),
        ('songs', '0002_remove_song_album_remove_song_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albumId',
            field=models.ForeignKey(db_column='albumId', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='userId',
            field=models.ForeignKey(db_column='userId', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
