# Generated by Django 5.1.6 on 2025-03-11 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_userid_album_user_remove_album_songs_and_more'),
        ('songs', '0004_alter_song_albumid_alter_song_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albumId',
        ),
        migrations.RemoveField(
            model_name='song',
            name='userId',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
