# Generated by Django 5.1.6 on 2025-03-13 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_song_album_alter_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='releaseDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
