# Generated by Django 5.1.6 on 2025-03-15 09:26

import Sportify_Server.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.JSONField(default=list, validators=[Sportify_Server.mixin.GenreMixin.validate_genres]),
        ),
    ]
