# Generated by Django 5.1.6 on 2025-03-17 09:18

import Sportify_Server.mixin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_album_primarygenre_alter_album_user'),
        ('songs', '0008_song_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.CharField(default=None, max_length=8000),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=255, validators=[Sportify_Server.mixin.GenreMixin.validate_genres]),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnailUrl',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
