# Generated by Django 5.1.6 on 2025-03-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_song_lyric_song_views_alter_song_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.CharField(default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnailUrl',
            field=models.URLField(),
        ),
    ]
