# Generated by Django 5.1.6 on 2025-03-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_song_lyric_alter_song_thumbnailurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyric',
            new_name='lyrics',
        ),
    ]
