# Generated by Django 5.1.6 on 2025-03-19 14:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('codeExpired', models.DateTimeField(default=datetime.datetime(2025, 3, 19, 14, 16, 52, 195175, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otps',
            },
        ),
    ]
