# Generated by Django 5.1.6 on 2025-03-19 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='codeExpired',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 14, 18, 18, 891816, tzinfo=datetime.timezone.utc)),
        ),
    ]
