# Generated by Django 5.1.6 on 2025-03-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='timeExpired',
            new_name='timeExpired',
        ),
    ]
