# Generated by Django 5.1.6 on 2025-05-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_content_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
